### PR TITLE
Changed boot path from "HackBGRT" to "BGRT"

### PR DESCRIPTION
**Pull request by beaujos**
- Changed boot path from "HackBGRT" to "BGRT"
- Updated new error strings

### CODE REVIEW

**Comment by sylveon** [comment]
y tho

**Comment by My1** [comment]
> y tho

sounds less hacky i guess?

**Comment by Metabolix** [comment]
Since it's 100% hacky anyway, I'm obviously not going to merge this.

**Comment by My1** [comment]
I fully agree, I think it's likely similar to Agent Ransack vs FileLocator Lite/Pro, literally the same software, twice but with a different name, with the latter one being a more "friendly" branding, but you arent trying to sell it anyway XD

**Pull request closed without merging**
